export default [
  {
    id: 0,
    name: 'Din Jarin',
    photo: './imgs/din-jarin.png',
    selected: false,
  },
  {
    id: 1,
    name: 'Grogu',
    photo: './imgs/baby-yoda.jpg',
    selected: false,
  },
  {
    id: 2,
    name: 'Darth vader',
    photo: './imgs/darth.webp',
    selected: false,
  },
  {
    id: 3,
    name: 'Luke Skywalker',
    photo: './imgs/luke.jpg',
    selected: false,
  },
  {
    id: 4,
    name: 'Boba Fett',
    photo: './imgs/boba-fett.jpg',
    selected: false,
  },
  {
    id: 5,
    name: 'Anakin Skywalker',
    photo: './imgs/anakin.webp',
    selected: false,
  },
  {
    id: 6,
    name: 'Ashoka tano',
    photo: './imgs/ashoka.webp',
    selected: false,
  },
  {
    id: 7,
    name: 'Chewbacca',
    photo: './imgs/chewbacca.webp',
    selected: false,
  },
  {
    id: 8,
    name: 'Clonetrooper',
    photo: './imgs/clonetrooper.jpg',
    selected: false,
  },
  {
    id: 9,
    name: 'darth Maul',
    photo: './imgs/darth-maul.jpg',
    selected: false,
  },
  {
    id: 10,
    name: 'Han Solo',
    photo: './imgs/han-solo.webp',
    selected: false,
  },
  {
    id: 11,
    name: 'Leia organa',
    photo: './imgs/leia.webp',
    selected: false,
  },
  {
    id: 12,
    name: 'Mace Windu',
    photo: './imgs/Mace-Windu.jpg',
    selected: false,
  },
  {
    id: 13,
    name: 'obi Wan Kenobi',
    photo: './imgs/obi-wan.webp',
    selected: false,
  },
  {
    id: 14,
    name: 'Emperor Palpatine',
    photo: './imgs/palpatine.jpg',
    selected: false,
  },
  {
    id: 15,
    name: 'qin-Gon Jinn',
    photo: './imgs/QuinGon.webp',
    selected: false,
  },
  {
    id: 16,
    name: 'R2-D2',
    photo: './imgs/r2d2.png',
    selected: false,
  },
  {
    id: 17,
    name: 'Stormtrooper',
    photo: './imgs/stormtrooper.webp',
    selected: false,
  },
  {
    id: 18,
    name: 'Yoda',
    photo: './imgs/yoda.webp',
    selected: false,
  },
];
